### ISSUE TITLE
VLAN interface without encapsulation is accepted by YANG model

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#162]
```
root@infix-00-00-00:/config/> edit interfaces interface vlan1
root@infix-00-00-00:/config/interfaces/interface/vlan1/> set  parent-interface brygga
root@infix-00-00-00:/config/interfaces/interface/vlan1/> leave 
root@infix-00-00-00:/> show interfaces 
INTERFACE       PROTOCOL   STATE       DATA                                     
brygga          ethernet   UP          02:00:00:00:00:00                        
└ e0            ethernet   UP          02:00:00:00:00:00                        
lo              ethernet   UP          00:00:00:00:00:00                        
                ipv4                   127.0.0.1/8 (static)
                ipv6                   ::1/128 (static)
Traceback (most recent call last):
  File "/lib/infix/cli-pretty", line 241, in <module>
    sys.exit(ietf_interfaces(json, args.name))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/infix/cli-pretty", line 229, in ietf_interfaces
    return pr_interface_list(json)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/infix/cli-pretty", line 209, in pr_interface_list
    iface.pr_vlan(ifaces)
  File "/lib/infix/cli-pretty", line 127, in pr_vlan
    self.pr_proto_eth()
  File "/lib/infix/cli-pretty", line 98, in pr_proto_eth
    dec = Decore.green if self.data['oper-status'] == "up" else Decore.red
                          ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'oper-status'
vlan1           
```

**Comment by troglobit** [comment]
@rical could you have a look at this to help classify it for v23.10?
